### ISSUE TITLE
Possible Example File Issue

### ISSUE THREAD

**Issue by kjsauer** [lbj2011/IVcorrection#1]
Hello, I would like to make sure the "example file" (example_file.xlsx) is in the correct format. It doesn't work w/ the below website. Namely, when you download and then upload it, it fails.

https://pvtools.lbl.gov/iv-curve-correction-tool

"There was an error processing this file."

**Comment by kjsauer** [comment]
@lbj2011: Any update on this? Thanks!

**Comment by lbj2011** [comment]
Thanks for letting me know the bug. I will work on it and reach back to you when it is solved. Currently, you can download the python package for local deployment of the tool.

**Comment by kjsauer** [comment]
Would you please upload the correct Excel file somewhere into the GitHub repository (with the correct formatting)? This way we don't have to reverse engineer the proper formatting of it based on the Python code. Thanks.

**Comment by lbj2011** [comment]
The upload and analysis function of the web is working now. Note that it only supports .csv file. The example file link is updated on the web and the file is also available here: https://github.com/lbj2011/IVcorrection/blob/main/examples/data/example.csv
